#!/bin/bash
#Pre-batch ingest surrogate data stream creation
#This script creates the lossless jp2
for f in $( ls );
do
  /usr/local/djatoka/bin/Linux-x86-64/kdu_compress -i "$f" -o  ../jp2_lossless/"$f".jp2 -rate -,0.5 Clayers=2 Creversible=yes Clevels=8 "Cprecincts={256,256},{256,256},{128,128}" Corder="RPCL" ORGgen_plt="yes" ORGtparts="R" Cblk="{32,32}"
done
